# cargo-about configuration. Generates the third-party license attribution
# (NOTICES) required by Apache-2.0 §4(d) when distributing the compiled binary.
# The accepted set mirrors the license allowlist in deny.toml; a dependency
# carrying anything outside it fails generation and forces a deliberate review.
accepted = [
	"Apache-2.0",
	"Apache-2.0 WITH LLVM-exception",
	"MIT",
	"0BSD",
	"BSD-1-Clause",
	"BSD-3-Clause",
	"BSL-1.0",
	"ISC",
	"Unicode-3.0",
	"Unlicense",
	"Zlib",
	"CC0-1.0",
	"CDLA-Permissive-2.0",
]
