name: CI

on:
  push:
    branches: [main, develop]
  pull_request:
    branches: [main, develop]

permissions:
  contents: read

jobs:
  rust:
    uses: Glyndor/.github/.github/workflows/rust-ci.yml@49b960ef2b033f8219e98b5314a5429c3d514a48 # main
    with:
      extra-test-os: '["macos-latest", "windows-latest"]'
      podman: true
      coverage-threshold: 90
