name: CI

on:
  push:
    branches: [main, develop]
  pull_request:
    branches: [main, develop]

permissions:
  contents: read

jobs:
  rust:
    uses: Glyndor/.github/.github/workflows/rust-ci.yml@13eb0e370e6aa227a37bbf45ca94a9a7a0c8281b # ci/rust-podman-latest (validation)
    with:
      extra-test-os: "[\"macos-latest\", \"windows-latest\"]"
      podman: true
      coverage-threshold: 90
      msrv: "1.85"
      package-check: true
      semver-check: true
      doc-warnings: true
