name: DCO

on:
  pull_request:
    branches:
      - main
      - develop

permissions:
  contents: read

jobs:
  dco:
    uses: Glyndor/.github/.github/workflows/dco.yml@ef351e0a6632c3688a32c524d09f56abb1c6e2ba # main
