name: DCO

on:
  pull_request:
    branches:
      - main
      - develop

permissions:
  contents: read

jobs:
  dco:
    uses: Glyndor/.github/.github/workflows/dco.yml@367c6651f8a8055085e7cb1e3c289e68f105e1c4 # v1.7.0
