name: Debian package

on:
  push:
    branches:
      - develop
    paths:
      - "debian/**"
      - "Cargo.toml"
      - "Cargo.lock"
      - "internal/**"
      - ".github/workflows/debian-build.yml"
  pull_request:
    branches:
      - main
      - develop
    paths:
      - "debian/**"
      - "Cargo.toml"
      - "Cargo.lock"
      - "internal/**"
      - ".github/workflows/debian-build.yml"

permissions:
  contents: read

jobs:
  debian:
    uses: Glyndor/.github/.github/workflows/rust-debian.yml@f72a52755c737ad4ae0a61e56ac43e2edc7280c5 # v1.1.0
    with:
      package-name: podup
      check-vendored: true
      offline-cargo-args: "--no-default-features --features watch,completions"
