name: Line limit

on:
  pull_request:
    branches:
      - main
      - develop

permissions:
  contents: read

jobs:
  line-limit:
    uses: Glyndor/.github/.github/workflows/line-limit.yml@505d78df893bfc2f73261ff285529e6afd46f5ac # v1.9.1
