name: Lint PowerShell scripts

on:
  push:
    branches:
      - develop
    paths:
      - "**.ps1"
      - ".github/workflows/lint-powershell.yml"
  pull_request:
    branches:
      - main
      - develop
    paths:
      - "**.ps1"
      - ".github/workflows/lint-powershell.yml"

permissions:
  contents: read

jobs:
  psscriptanalyzer:
    name: PSScriptAnalyzer
    uses: Glyndor/.github/.github/workflows/powershell-ci.yml@7f386e098ac242fc82e2e9a2b5e02c50cf00eedf # v1.10.0-pre
    with:
      paths: "install.ps1"
