name: Lint shell scripts

on:
  push:
    branches:
      - develop
    paths:
      - "**.sh"
      - ".github/workflows/lint-shell.yml"
  pull_request:
    branches:
      - main
      - develop
    paths:
      - "**.sh"
      - ".github/workflows/lint-shell.yml"

permissions:
  contents: read

jobs:
  shellcheck:
    uses: Glyndor/.github/.github/workflows/shell-ci.yml@e22b97f79921a0a1d37d18d91e0ce62aac4f56cd # v1.9.0
