name: Lint shell scripts

on:
  push:
    branches:
      - develop
    paths:
      - "**.sh"
      - ".github/workflows/lint-shell.yml"
  pull_request:
    branches:
      - main
      - develop
    paths:
      - "**.sh"
      - ".github/workflows/lint-shell.yml"

permissions:
  contents: read

jobs:
  shellcheck:
    uses: Glyndor/.github/.github/workflows/shell-ci.yml@367c6651f8a8055085e7cb1e3c289e68f105e1c4 # v1.7.0
