name: guard

on:
  pull_request:
    branches: ["main"]

permissions: {}

jobs:
  develop-only:
    uses: Glyndor-net/.github/.github/workflows/main-guard.yml@367c6651f8a8055085e7cb1e3c289e68f105e1c4 # v1.7.0
