name: guard

on:
  pull_request:
    branches: ["main"]

permissions: {}

jobs:
  develop-only:
    uses: Glyndor/.github/.github/workflows/main-guard.yml@91a23397a14f0efb46e2b354d72df0e10a0004b6 # main
