name: guard

on:
  pull_request:
    branches: ["main"]

permissions: {}

jobs:
  develop-only:
    uses: Glyndor/.github/.github/workflows/main-guard.yml@f72a52755c737ad4ae0a61e56ac43e2edc7280c5 # v1.1.0
