name: Supply chain

on:
  pull_request:
    branches:
      - main
      - develop
    paths:
      - "Cargo.toml"
      - "Cargo.lock"
      - "about.toml"
      - "about.hbs"
      - ".github/workflows/supply-chain.yml"
  push:
    branches:
      - develop

permissions:
  contents: read

jobs:
  supply-chain:
    uses: Glyndor/.github/.github/workflows/rust-supply-chain.yml@b78620146d50fdbc552e1b86740e64d114c58f0f # v1.0.0
