name: Supply chain

on:
  pull_request:
    branches:
      - main
      - develop
    paths:
      - "Cargo.toml"
      - "Cargo.lock"
      - "about.toml"
      - "about.hbs"
      - ".github/workflows/supply-chain.yml"
  push:
    branches:
      - develop

permissions:
  contents: read

jobs:
  supply-chain:
    uses: Glyndor/.github/.github/workflows/rust-supply-chain.yml@ef351e0a6632c3688a32c524d09f56abb1c6e2ba # main
