name: Supply chain

on:
  pull_request:
    branches:
      - main
      - develop
    paths:
      - "Cargo.toml"
      - "Cargo.lock"
      - "about.toml"
      - "about.hbs"
      - ".github/workflows/supply-chain.yml"
  push:
    branches:
      - develop

permissions:
  contents: read

jobs:
  supply-chain:
    uses: Glyndor/.github/.github/workflows/rust-supply-chain.yml@b12b4c0bb5c2caec50ea8e46a21a5c0519b73ad9 # v1.10.0-pre
